### ISSUE TITLE
This program have viruses (sorry, i know english not very good)

### ISSUE THREAD

**Issue by NullPointerExceptionBruh** [nimaid/binary-waterfall#14]
![image](https://github.com/nimaid/binary-waterfall/assets/145906200/b330b368-e078-436b-a5a8-9c7f6c8a3b90)
why virus detected?

**Comment by nimaid** [comment]
Thank you for reaching out! Based on my research, this is a common false positive. In my scans, only 2 obscure anti viruses picked this up.

Considering that 98% of antiviruses (including all big name ones) say this is clean, I have to assume the false positives were based on heuristic or AI analysis that misinterpreted the behavior of the code as malicious for some reason.

If you have any new information which may indicate a legitimate threat somehow slipped into the .exe, please open a new issue. I'm closing this issue due to the high likelihood of this being a false positive.
